# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 21:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.IntegerField(db_column='telefono', null=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=145)),
                ('documento', models.IntegerField(db_column='documento')),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('precio', models.IntegerField(db_column='precio')),
                ('comentario', models.CharField(db_column='comentario', max_length=100)),
            ],
            options={
                'db_table': 'platillos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=45)),
                ('sitioweb', models.CharField(db_column='sitioweb', max_length=45)),
            ],
            options={
                'db_table': 'restaurante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.IntegerField(db_column='telefono', null=True)),
                ('direccion', models.CharField(db_column='direccion', max_length=45)),
                ('documento', models.IntegerField(db_column='documento')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario_Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usuarios_restaurante',
                'managed': False,
            },
        ),
    ]
