# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(db_column='comentarios')),
                ('approved_comment', models.BooleanField(db_column='aprobado', default=False)),
            ],
            options={
                'db_table': 'usuarios_restaurante',
                'managed': False,
            },
        ),
    ]
